import { ChevronLeft, ChevronRight, ExternalLink, Loader2 } from "lucide-react";
import type { LiveMarket, LiveMarketListing } from "@/lib/market";

const FB_LOGO = `${import.meta.env.BASE_URL}assets/brand/social/fractal-bitcoin.png`;
const fb = (value: number | null) => value == null ? "—" : `${value.toLocaleString(undefined, { maximumFractionDigits: 4 })} FB`;
const usd = (value: number | null, fbPrice: number | null = null, fbUsd: number | null = null) => { const resolved = value ?? (fbPrice != null && fbUsd != null ? fbPrice * fbUsd : null); return resolved == null ? "—" : `$${resolved.toLocaleString(undefined, { maximumFractionDigits: 2 })}`; };
const satsToFb = (value: number | null) => value == null ? null : value / 100_000_000;

export function MarketPanel({ market, loading, error, page, onPage, imageForListing }: { market: LiveMarket | null; loading: boolean; error: string; page: number; onPage: (page: number) => void; imageForListing?: (item: LiveMarketListing) => string | null }) {
  const stats = market?.stats;
  return <section className="border-b border-[#2c323a] bg-[#10151a] px-5 py-5 sm:px-8 lg:px-12" aria-label="Live collection market">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#d99a54]">Live market / FB</p><h2 className="mt-2 font-display text-2xl font-semibold text-[#f3efe5]">Collection market</h2></div><span className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#718092]">Powered by UniSat · {market ? new Date(market.refreshedAt).toLocaleTimeString() : "refreshing"}</span></div>
    <div className="mt-5 grid grid-cols-2 gap-px border border-[#2c323a] bg-[#2c323a] sm:grid-cols-4">
      {[["Total volume", fb(stats?.volumeTotalFb ?? null), usd(stats?.volumeTotalUsd ?? null, stats?.volumeTotalFb ?? null, market?.fbUsd)], ["24h volume", fb(stats?.volume24hFb ?? null), usd(stats?.volume24hUsd ?? null, stats?.volume24hFb ?? null, market?.fbUsd)], ["Floor price", fb(stats?.floorFb ?? null), usd(stats?.floorUsd ?? null, stats?.floorFb ?? null, market?.fbUsd)], ["Market cap", fb(stats?.marketCapFb ?? null), usd(stats?.marketCapUsd ?? null, stats?.marketCapFb ?? null, market?.fbUsd)]].map(([label, main, secondary]) => <div key={label} className="bg-[#14191f] p-3 sm:p-4"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-[#718092]">{label}</p><p className="mt-2 flex items-center gap-1 font-mono text-sm text-[#f2bd63]"><img src={FB_LOGO} alt="FB" className="h-4 w-4 rounded-full object-cover" />{main}</p><p className="mt-1 flex items-center gap-1 font-mono text-[10px] text-[#9ea7b3]"><span className="inline-flex h-4 w-4 items-center justify-center rounded-full border border-[#718092] text-[9px]">$</span>{secondary}</p></div>)}
    </div>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#9ea7b3]">Listed tokens · {market?.totalListings ?? 0}</p><div className="flex items-center gap-2"><button type="button" disabled={page === 0 || loading} onClick={() => onPage(page - 1)} className="border border-[#3b434d] p-2 text-[#9ea7b3] disabled:opacity-30" aria-label="Previous listed tokens"><ChevronLeft size={14} /></button><span className="font-mono text-[10px] text-[#718092]">Page {page + 1}</span><button type="button" disabled={!market || (page + 1) * 20 >= market.totalListings || loading} onClick={() => onPage(page + 1)} className="border border-[#3b434d] p-2 text-[#9ea7b3] disabled:opacity-30" aria-label="Next listed tokens"><ChevronRight size={14} /></button></div></div>
    {loading && !market ? <div className="mt-4 flex items-center gap-2 font-mono text-[10px] text-[#9ea7b3]"><Loader2 size={14} className="animate-spin text-[#d99a54]" /> Loading live listings…</div> : error ? <p className="mt-4 font-mono text-[10px] text-[#a45e54]">{error}</p> : <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{market?.listings.map((item) => <a key={item.inscriptionId} href={`https://fractal.unisat.io/inscription/${item.inscriptionId}`} target="_blank" rel="noreferrer" className="border border-[#2c323a] bg-[#14191f] p-3 transition-colors hover:border-[#d99a54]/70"><div className="mb-2 aspect-square overflow-hidden bg-[#171b21]"><>{imageForListing?.(item) ? <img src={imageForListing(item) as string} alt={`${item.collectionItemName || "Listed token"} artwork`} className="h-full w-full object-cover" loading="lazy" /> : <div className="flex h-full items-center justify-center font-mono text-[9px] uppercase text-[#718092]">Artwork unavailable</div>}</></div><div className="flex items-center justify-between gap-2"><span className="truncate font-sans text-xs text-[#f3efe5]">{item.collectionItemName || item.inscriptionId.slice(0, 10)}</span><ExternalLink size={12} className="shrink-0 text-[#d99a54]" /></div><p className="mt-2 font-mono text-xs text-[#f2bd63]">{fb(item.priceFb ?? satsToFb(item.priceSats))}</p><p className="mt-1 font-mono text-[10px] text-[#9ea7b3]">{usd(item.priceUsd, item.priceFb ?? satsToFb(item.priceSats), market?.fbUsd)} · {item.marketType || "fixedPrice"}</p></a>)}</div>}
  </section>;
}
